name: ChangeLog

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 
    - name: Checkout Tool
      uses: actions/checkout@v2
      with:
        repository: konakonall/auto-changelog
        path: 'auto-changelog'
    - name: Build Tool
      run: |
        cd auto-changelog
        npm install
        npm link
    - name: Generate ChangeLog
      env: # Or as an environment variable
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        auto-changelog --token $TOKEN
    - name: Cat ChangeLog
      run: cat CHANGELOG.md
